Update Push-Multi-Target Build AmneziaWG.yml

diff --git a/.github/workflows/Push-Multi-Target Build AmneziaWG.yml b/.github/workflows/Push-Multi-Target Build AmneziaWG.yml
--- a/.github/workflows/Push-Multi-Target Build AmneziaWG.yml
+++ b/.github/workflows/Push-Multi-Target Build AmneziaWG.yml
@@ -78,6 +78,9 @@ jobs:
             TARGET="${{ matrix.target }}"
             SUBTARGET="${{ matrix.subtarget }}"
 
+            git config --global http.postBuffer 524288000
+            git config --global http.maxRequests 100
+
             if [ "$VERSION" = "SNAPSHOT" ]; then
                 MIRRORS=("https://downloads.openwrt.org/snapshots/targets/$TARGET/$SUBTARGET")
             else
@@ -113,7 +116,9 @@ jobs:
             mv openwrt-sdk* openwrt
 
             echo "src-cpy awgopenwrt ../amneziawg" >> openwrt/feeds.conf.default
-            ./openwrt/scripts/feeds update -a
+            for i in {1..3}; do
+              ./openwrt/scripts/feeds update -a && break || echo "Feeds update failed, retry $i"
+            done
 
             curl -fsL "$BASE_URL/config.buildinfo" > openwrt/.config
             echo "CONFIG_PACKAGE_kmod-crypto-kpp=y" >> openwrt/.config
